//
//  ContactInteractor.swift
//  Contact
//
//  Created by zs-mac-4 on 19/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol ContactBusinessLogic:AnyObject
{
    func fetchContacts()
}

class ContactInteractor: ContactBusinessLogic
{
    
    let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext
    
    func fetchContacts() {
        let fetchRequest = NSFetchRequest<NSFetchRequestResult>(entityName: "ContactInfo")
        do{
            let result = try? context.fetch(fetchRequest)
            let contacts = result as! [NSManagedObject]
            let resultContacts = contact.Request(contacts: contacts)
            presenter?.presentContacts(contacts: resultContacts)
            
           
            }
            

    }
    
  var presenter: ContactPresentationLogic?
    
    
 
}
